modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mododjooj"
version="1.0.0"
displayName="Mododjooj"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Thiago Salustiano, MCreator"

[[dependencies.mododjooj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




